server:
  # 80表示注册到zookeeper服务器的顶单服务消费者端口号
  port: 80
spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-consumer-payment
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: 47.98.44.56:2181